version: '3.8'

services:
  solana-node:
    build:
      context: .
      dockerfile: Dockerfile.solana
    platform: linux/amd64
    container_name: solana-node
    ports:
      - "8899:8899"
      - "8900:8900"
      - "9900:9900"
    volumes:
      - solana-data:/root/.config/solana
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "-H", "Content-Type: application/json", "-d", "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"getHealth\"}", "http://localhost:8899"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

volumes:
  solana-data: